from __future__ import annotations

from .base import (
    BatchSegmentationProvider,
    BatchSegmentationRequest,
    CompressionOutcome,
    Exporter,
    ExportProvider,
    LLMProvider,
    MaskProvider,
    MattingProvider,
    ObjectCandidateProvider,
    PhaseTiming,
    ProviderConfigError,
    ProviderError,
    ProviderExecutionError,
    ProviderAttempt,
    RenderProvider,
    SegmentationProvider,
    StorageProvider,
    TrackLinker,
    Vectorizer,
    VideoTracker,
)
from .mask_cache import MaskCache, normalize_binary_mask
from .local_storage import LocalStorageProvider
from .discovery import (
    DISCOVERY_MODES,
    DISCOVERY_PROVIDER_SCHEMAS,
    ClassDetectorDiscoveryProvider,
    ExternalMasksDiscoveryProvider,
    ManualPromptDiscoveryProvider,
    MockObjectDiscoveryProvider,
    MotionForegroundDiscoveryProvider,
    SAM2AutomaticProposalDiscoveryProvider,
    SAM3AutoMasksDiscoveryProvider,
    SAM3ConceptDiscoveryProvider,
    SAM3ExemplarDiscoveryProvider,
    SamAutoMasksDiscoveryProvider,
    TextDetectorDiscoveryProvider,
    class_detector_presets,
    discovery_provider_schemas,
    object_specs_from_candidates,
)
from .mocks import (
    MockExportProvider,
    MockLLMProvider,
    MockMaskProvider,
    MockMattingProvider,
    MockObjectCandidateProvider,
    MockPipelineExporter,
    MockRenderProvider,
    MockSegmentationProvider,
    MockStorageProvider,
    MockTrackLinker,
    MockVectorizer,
    MockVideoTracker,
)
from .pipeline_adapters import (
    ContourVectorizer,
    IdentityTrackLinker,
    ManualPromptCandidateProvider,
    MotionJSONArtifactExporter,
    ObjectSpecCandidateProvider,
    ObjectSpecInitialMaskProvider,
    PerFrameMaskVideoTracker,
)
from .sam2 import (
    HostedSAM2SegmentationProvider,
    LocalSAM2AutomaticMaskProposalBackend,
    LocalSAM2SegmentationProvider,
    SAM2HostedSegmentationProvider,
    SAM2LocalAutomaticMaskProposalBackend,
    SAM2LocalSegmentationProvider,
)
from .sam3 import LocalSAM3DiscoveryBackend, SAM3LocalDiscoveryBackend
from .segmentation import FallbackSegmentationProvider, MaskProviderSegmentationAdapter, SegmentationMaskProvider, as_segmentation_provider

__all__ = [
    "ExportProvider",
    "BatchSegmentationProvider",
    "BatchSegmentationRequest",
    "CompressionOutcome",
    "ContourVectorizer",
    "DISCOVERY_MODES",
    "DISCOVERY_PROVIDER_SCHEMAS",
    "ClassDetectorDiscoveryProvider",
    "Exporter",
    "ExternalMasksDiscoveryProvider",
    "FallbackSegmentationProvider",
    "HostedSAM2SegmentationProvider",
    "IdentityTrackLinker",
    "LLMProvider",
    "LocalSAM2SegmentationProvider",
    "LocalSAM2AutomaticMaskProposalBackend",
    "LocalSAM3DiscoveryBackend",
    "LocalStorageProvider",
    "MaskCache",
    "MaskProvider",
    "MaskProviderSegmentationAdapter",
    "MattingProvider",
    "ManualPromptCandidateProvider",
    "ManualPromptDiscoveryProvider",
    "MotionForegroundDiscoveryProvider",
    "MotionJSONArtifactExporter",
    "MockExportProvider",
    "MockLLMProvider",
    "MockMaskProvider",
    "MockMattingProvider",
    "MockObjectCandidateProvider",
    "MockObjectDiscoveryProvider",
    "MockPipelineExporter",
    "MockRenderProvider",
    "MockSegmentationProvider",
    "MockStorageProvider",
    "MockTrackLinker",
    "MockVectorizer",
    "MockVideoTracker",
    "OpenRouterLLMProvider",
    "ObjectCandidateProvider",
    "ObjectSpecCandidateProvider",
    "ObjectSpecInitialMaskProvider",
    "PerFrameMaskVideoTracker",
    "ProviderConfigError",
    "ProviderError",
    "ProviderExecutionError",
    "PhaseTiming",
    "ProviderAttempt",
    "RenderProvider",
    "SAM2HostedSegmentationProvider",
    "SAM2LocalAutomaticMaskProposalBackend",
    "SAM2AutomaticProposalDiscoveryProvider",
    "SAM3AutoMasksDiscoveryProvider",
    "SAM3ConceptDiscoveryProvider",
    "SAM3ExemplarDiscoveryProvider",
    "SAM3LocalDiscoveryBackend",
    "SAM2LocalSegmentationProvider",
    "SamAutoMasksDiscoveryProvider",
    "SegmentationMaskProvider",
    "SegmentationProvider",
    "StorageProvider",
    "TextDetectorDiscoveryProvider",
    "TrackLinker",
    "Vectorizer",
    "VideoTracker",
    "as_segmentation_provider",
    "class_detector_presets",
    "discovery_provider_schemas",
    "normalize_binary_mask",
    "object_specs_from_candidates",
]


def __getattr__(name: str):
    if name == "OpenRouterLLMProvider":
        from .openrouter import OpenRouterLLMProvider

        return OpenRouterLLMProvider
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
